---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 2019/8/22 10:23 AM
---


--eval "return redis.call('set',KEYS[1],ARGV[1])"
--
--if redis.call(get,KEYS[1]) == false then
--
--    redis.call(set,KEYS[1],ARGV[1])
--    redis.call(expire,KEYS[1],ARGV[2])
--    return 0
--else
--    return 1
--end


--return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}


local key = KEYS[1]

local list = redis.call('lrange',key,0,-1);

return list;

